# Generated by Django 4.0.5 on 2022-07-03 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField(blank=True, default=0, null=True)),
                ('address', models.CharField(default=None, max_length=200)),
                ('major_health_issue', models.CharField(default=None, max_length=200, null=True)),
                ('blood_group', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('verification_code', models.CharField(max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_removed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=0)),
                ('updated_at', models.DateTimeField(null=True)),
                ('removed_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'app_users',
            },
        ),
        migrations.CreateModel(
            name='HealthStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_issue', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('is_removed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=0)),
                ('updated_at', models.DateTimeField(null=True)),
                ('removed_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccapp.appuser')),
            ],
            options={
                'db_table': 'app_health_status',
            },
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_title', models.CharField(max_length=100)),
                ('diet_plan', models.TextField(max_length=500)),
                ('diet_duration', models.CharField(max_length=200)),
                ('medicine_details', models.TextField(max_length=500)),
                ('remarks', models.TextField(max_length=500)),
                ('is_removed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=0)),
                ('updated_at', models.DateTimeField(null=True)),
                ('removed_at', models.DateTimeField(null=True)),
                ('health_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccapp.healthstatus')),
            ],
            options={
                'db_table': 'diet_recomendation',
            },
        ),
    ]
